[2016-03-20 21:43:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /test_api/index.php"" at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php line 176 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /test_api/index.php\" at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php:176, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 18:05:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /test_api/index.php"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /test_api/index.php\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 18:12:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /new"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /new\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 18:13:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /new"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /new\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 18:13:11] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /new"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /new\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 18:13:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login_check"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login_check\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 18:14:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /login_check"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /login_check\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:39)"} []
[2016-03-21 22:23:41] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://apibase.start/login_check"} []
[2016-03-21 22:23:41] security.INFO: User has been authenticated successfully. {"username":"teo"} []
[2016-03-21 22:23:41] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\EventListener\JWTResponseListener' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":1125,"level":6143,"stack":[]} []
[2016-03-21 22:23:42] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "JWTResponseListener" from namespace "SB\UserBundle\EventListener". Did you forget a "use" statement for another namespace?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 1125 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"JWTResponseListener\" from namespace \"SB\\UserBundle\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:1125)"} []
[2016-03-21 22:25:07] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://apibase.start/login_check"} []
[2016-03-21 22:25:08] security.INFO: User has been authenticated successfully. {"username":"teo"} []
[2016-03-21 22:25:08] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\EventListener\JWTResponseListener' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":1125,"level":6143,"stack":[]} []
[2016-03-21 22:25:08] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "JWTResponseListener" from namespace "SB\UserBundle\EventListener". Did you forget a "use" statement for another namespace?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 1125 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"JWTResponseListener\" from namespace \"SB\\UserBundle\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:1125)"} []
[2016-03-21 22:26:14] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://apibase.start/login_check"} []
[2016-03-21 22:26:15] security.INFO: User has been authenticated successfully. {"username":"teo"} []
[2016-03-21 22:26:15] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\EventListener\AuthenticationSuccessListener' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":1125,"level":6143,"stack":[]} []
[2016-03-21 22:26:15] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "AuthenticationSuccessListener" from namespace "SB\UserBundle\EventListener". Did you forget a "use" statement for another namespace?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 1125 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AuthenticationSuccessListener\" from namespace \"SB\\UserBundle\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:1125)"} []
[2016-03-21 22:26:18] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://apibase.start/login_check"} []
[2016-03-21 22:26:19] security.INFO: User has been authenticated successfully. {"username":"teo"} []
[2016-03-21 22:26:19] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\EventListener\AuthenticationSuccessListener' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":1125,"level":6143,"stack":[]} []
[2016-03-21 22:26:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "AuthenticationSuccessListener" from namespace "SB\UserBundle\EventListener". Did you forget a "use" statement for another namespace?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 1125 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AuthenticationSuccessListener\" from namespace \"SB\\UserBundle\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:1125)"} []
[2016-03-21 22:26:32] request.INFO: Matched route "login_check". {"route_parameters":{"_route":"login_check"},"request_uri":"http://apibase.start/login_check"} []
[2016-03-21 22:26:33] security.INFO: User has been authenticated successfully. {"username":"teo"} []
[2016-03-21 22:26:33] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\EventListener\AuthenticationSuccessListener' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":1125,"level":6143,"stack":[]} []
[2016-03-21 22:26:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "AuthenticationSuccessListener" from namespace "SB\UserBundle\EventListener". Did you forget a "use" statement for another namespace?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 1125 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AuthenticationSuccessListener\" from namespace \"SB\\UserBundle\\EventListener\".\nDid you forget a \"use\" statement for another namespace? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:1125)"} []
[2016-03-22 14:29:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /user"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /user\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:44)"} []
[2016-03-22 14:29:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /user"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /user\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:44)"} []
[2016-03-22 14:29:04] request.CRITICAL: Exception thrown when handling an exception (RuntimeException: Unable to create the cache directory (/var/www/apibase.start/app/cache/prod/twig/80). at /var/www/apibase.start/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 60) {"exception":"[object] (RuntimeException(code: 0): Unable to create the cache directory (/var/www/apibase.start/app/cache/prod/twig/80). at /var/www/apibase.start/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:60)"} []
[2016-03-22 14:29:04] php.CRITICAL: Uncaught Exception: Unable to create the cache directory (/var/www/apibase.start/app/cache/prod/twig/80). {"type":1,"file":"/var/www/apibase.start/vendor/twig/twig/lib/Twig/Cache/Filesystem.php","line":60,"level":6143,"stack":[{"file":"/var/www/apibase.start/app/cache/prod/classes.php","line":3740,"function":"write","class":"Twig_Cache_Filesystem","type":"->","args":["/var/www/apibase.start/app/cache/prod/twig/80/80e330a9cbf31b30ea2a235843e3911a9774c89742d473e65096355734e505f2.php","<?php\n\n/* @Twig/Exception/error.json.twig */\nclass __TwigTemplate_6d6d42ab1e73a1ceb615bda988ba7fda73fa1b361eb83599232a0b760ab96448 extends Twig_Template\n{\n    public function __construct(Twig_Environment $env)\n    {\n        parent::__construct($env);\n\n        $this->parent = false;\n\n        $this->blocks = array(\n        );\n    }\n\n    protected function doDisplay(array $context, array $blocks = array())\n    {\n        // line 1\n        echo twig_jsonencode_filter(array(\"error\" => array(\"code\" => (isset($context[\"status_code\"]) ? $context[\"status_code\"] : null), \"message\" => (isset($context[\"status_text\"]) ? $context[\"status_text\"] : null))));\n        echo \"\n\";\n    }\n\n    public function getTemplateName()\n    {\n        return \"@Twig/Exception/error.json.twig\";\n    }\n\n    public function isTraitable()\n    {\n        return false;\n    }\n\n    public function getDebugInfo()\n    {\n        return array (  19 => 1,);\n    }\n}\n/* {{ { 'error': { 'code': status_code, 'message': status_text } }|json_encode|raw }}*/\n/* */\n"]},{"file":"/var/www/apibase.start/app/cache/prod/classes.php","line":3714,"function":"loadTemplate","class":"Twig_Environment","type":"->","args":["@Twig/Exception/error.json.twig"]},{"file":"/var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php","line":72,"function":"render","class":"Twig_Environment","type":"->","args":["@Twig/Exception/error.json.twig",{"status_code":404,"status_text":"Not Found","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FlattenException: {})","logger":"[object] (Symfony\\Bridge\\Monolog\\Logger: {})","currentContent":""}]},{"function":"showAction","class":"Symfony\\Bundle\\TwigBundle\\Controller\\ExceptionController","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})","[object] (Symfony\\Component\\Debug\\Exception\\FlattenException: {})","[object] (Symfony\\Bridge\\Monolog\\Logger: {})"]},{"file":"/var/www/apibase.start/app/bootstrap.php.cache","line":2687,"function":"call_user_func_array","args":[["[object] (Symfony\\Bundle\\TwigBundle\\Controller\\ExceptionController: {})","showAction"],["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})","[object] (Symfony\\Component\\Debug\\Exception\\FlattenException: {})","[object] (Symfony\\Bridge\\Monolog\\Logger: {})"]]},{"file":"/var/www/apibase.start/app/bootstrap.php.cache","line":2649,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})",2]},{"file":"/var/www/apibase.start/app/bootstrap.php.cache","line":2800,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})",2,false]},{"file":"/var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php","line":50,"function":"handle","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})",2,false]},{"function":"onKernelException","class":"Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener","type":"->","args":["[object] (Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent: {})","kernel.exception","[object] (Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher: {})"]},{"file":"/var/www/apibase.start/app/cache/prod/classes.php","line":2343,"function":"call_user_func","args":[["[object] (Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener: {})","onKernelException"],"[object] (Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent: {})","kernel.exception","[object] (Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher: {})"]},{"file":"/var/www/apibase.start/app/cache/prod/classes.php","line":2261,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[["[object] (FOS\\RestBundle\\EventListener\\AccessDeniedListener: {})","onKernelException"],["[object] (Symfony\\Component\\HttpKernel\\EventListener\\ExceptionListener: {})","onKernelException"]],"kernel.exception","[object] (Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent: {})"]},{"file":"/var/www/apibase.start/app/bootstrap.php.cache","line":2719,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["kernel.exception","[object] (Symfony\\Component\\HttpKernel\\Event\\GetResponseForExceptionEvent: {})"]},{"file":"/var/www/apibase.start/app/bootstrap.php.cache","line":2655,"function":"handleException","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":["[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /user\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:44)","[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})",1]},{"file":"/var/www/apibase.start/app/bootstrap.php.cache","line":2800,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})",1,true]},{"file":"/var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php","line":185,"function":"handle","class":"Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})",1,true]},{"file":"/var/www/apibase.start/web/app.php","line":30,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","args":["[object] (Symfony\\Component\\HttpFoundation\\Request: GET /user HTTP/1.0\r\nAuthorization:  Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0NTg2OTQ4MDAsInVzZXJuYW1lIjoidGVvIiwiaXAiOiIxMjcuMC4wLjEiLCJpYXQiOiIxNDU4NjUzMzAxIn0.IYsZm-EfMoS6hG_hsydux6w44PkJ1e9acMuXcVlCTNaVJCVgENNN2USjPlG8-ajA72c7-rlu85WpKFC9idy9yQ5ft903wRU66XFRK_uP-TTBa9hc3GhfIweki81KF_zWzNjqEoCRkLWviNCIwGAYYIbDWe-04wt1BJ6pl2efu9OW-OZOPsiqyJOj89z2GbG0Tej9vF2C7O6CLX7lJ7lyikC3JqY4jQbxNsBKKMkJlRWEr2uO4s_Xq4lRePwAj7oPKzgWMpK5sK-wsgD6axREA7FJSBzC0mm16tBjqndyKZq3VGqmM2zm_yb8UL7huMx6KcXgo4dyua_eDhI1E2aS34xVifCxyqiwd0v946ZoHHyUek9QJTa70WAMPw--sy02zDXKhGihzMcWQ9BYb0MbTC4uswGgxET2z2945gqZnVHFEvtV_7-_93K83zoQMhBDGNkLwGu5mHgb_1aARxZOFY36TEdo6QQsiNyyJ3uV5tH1tEA5Aul59zuV1MhpNgx0GYzF5eQFaAkmMHd2KoVut-iMKci5DLRhJ-EW00LbOWITyWvrHpXFxHzmZ186lhaND2Qbf8P4l0tTyU7Atyv1UgucEqSheLPzR1QvzKajZ5oOF0ZznyRmBRLMayNS0NehHoW_lP7uNBlzt2nDWE-AN80YuR88h4Lsf5bRqxwNRn8\r\nConnection:     close\r\nContent-Length: 21\r\nContent-Type:   application/json\r\nHost:           apibase.start\r\nX-Php-Ob-Level: 1\r\n\r\n{\"app_id\":\"eb42cd2c\"})"]}]} []
[2016-03-22 14:29:04] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the cache directory (/var/www/apibase.start/app/cache/prod/twig/80)." at /var/www/apibase.start/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 60 {"exception":"[object] (RuntimeException(code: 0): Unable to create the cache directory (/var/www/apibase.start/app/cache/prod/twig/80). at /var/www/apibase.start/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:60, Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /user\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:44)"} []
[2016-03-22 19:06:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /new"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /new\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:55)"} []
[2016-03-22 19:06:32] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:06:32] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "fos_user.registration.form.factory"." at /var/www/apibase.start/app/bootstrap.php.cache line 2181 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"fos_user.registration.form.factory\". at /var/www/apibase.start/app/bootstrap.php.cache:2181)"} []
[2016-03-22 19:06:54] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:06:55] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "fos_user.registration.form.factory"." at /var/www/apibase.start/app/bootstrap.php.cache line 2181 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"fos_user.registration.form.factory\". at /var/www/apibase.start/app/bootstrap.php.cache:2181)"} []
[2016-03-22 19:07:27] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:07:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "fos_user.registration.form.factory"." at /var/www/apibase.start/app/bootstrap.php.cache line 2181 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"fos_user.registration.form.factory\". at /var/www/apibase.start/app/bootstrap.php.cache:2181)"} []
[2016-03-22 19:07:46] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:07:46] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "fos_user.registration.form.factory"." at /var/www/apibase.start/app/bootstrap.php.cache line 2181 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"fos_user.registration.form.factory\". at /var/www/apibase.start/app/bootstrap.php.cache:2181)"} []
[2016-03-22 19:11:48] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:11:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 19:51:13] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:51:13] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 19:51:29] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:51:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 19:53:01] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:53:01] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 19:53:02] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:53:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 19:59:28] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 19:59:28] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 20:00:11] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 20:00:11] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 20:17:26] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 20:17:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 20:18:27] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 20:18:27] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 20:18:49] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 20:18:50] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-22 20:25:39] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-22 20:25:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 18:43:20] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 18:43:20] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 18:43:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 18:43:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 18:46:14] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 18:46:14] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 18:46:30] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 18:46:30] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 18:47:09] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 18:47:09] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 18:49:06] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 18:49:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 20:33:14] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 20:33:14] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 20:36:32] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 20:36:32] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-23 21:03:16] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-23 21:03:16] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 09:55:12] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 09:55:12] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 09:55:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 09:55:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 09:55:33] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 09:55:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:00:31] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:00:31] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "SB\UserBundle\Controller\UserController::newUserAction" for URI "/new" is not callable." at /var/www/apibase.start/app/cache/prod/classes.php line 2651 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"SB\\UserBundle\\Controller\\UserController::newUserAction\" for URI \"/new\" is not callable. at /var/www/apibase.start/app/cache/prod/classes.php:2651)"} []
[2016-03-26 10:01:12] request.INFO: Matched route "api_v1_users_new_user". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::newUserAction","_format":"json","_route":"api_v1_users_new_user"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:01:12] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "SB\UserBundle\Controller\UserController::newUserAction" for URI "/new" is not callable." at /var/www/apibase.start/app/cache/prod/classes.php line 2651 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"SB\\UserBundle\\Controller\\UserController::newUserAction\" for URI \"/new\" is not callable. at /var/www/apibase.start/app/cache/prod/classes.php:2651)"} []
[2016-03-26 10:01:28] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:01:28] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:01:42] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:01:42] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:02:09] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:02:09] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:06:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /app_dev/test_api/index.php"" at /var/www/apibase.start/app/cache/prod/classes.php line 2590 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /app_dev/test_api/index.php\" at /var/www/apibase.start/app/cache/prod/classes.php:2590, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/apibase.start/app/cache/prod/appProdUrlMatcher.php:99)"} []
[2016-03-26 10:24:39] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:24:39] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:25:00] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:25:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:25:00] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:25:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 10:25:33] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 10:25:34] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "SB\UserBundle\Entity\User"." at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 379 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"name\" nor one of the methods \"getName()\", \"name()\", \"isName()\", \"hasName()\", \"__get()\" exist and have public access in class \"SB\\UserBundle\\Entity\\User\". at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:379)"} []
[2016-03-26 11:52:23] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 11:52:24] php.CRITICAL: Fatal Error: Call to a member function get() on null {"type":1,"file":"/var/www/apibase.start/src/SB/UserBundle/Controller/UserController.php","line":55,"level":6143,"stack":[]} []
[2016-03-26 11:52:24] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Call to a member function get() on null" at /var/www/apibase.start/src/SB/UserBundle/Controller/UserController.php line 55 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function get() on null at /var/www/apibase.start/src/SB/UserBundle/Controller/UserController.php:55)"} []
[2016-03-26 22:03:21] request.INFO: Matched route "api_v1_users_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\UserController::registerAction","_format":"json","_route":"api_v1_users_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-26 22:03:21] php.CRITICAL: Fatal Error: Call to undefined method SB\UserBundle\Entity\User::unserialized() {"type":1,"file":"/var/www/apibase.start/src/SB/UserBundle/Controller/UserController.php","line":63,"level":6143,"stack":[]} []
[2016-03-26 22:03:21] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "unserialized" of class "SB\UserBundle\Entity\User". Did you mean to call e.g. "serialize" or "unserialize"?" at /var/www/apibase.start/src/SB/UserBundle/Controller/UserController.php line 63 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"unserialized\" of class \"SB\\UserBundle\\Entity\\User\".\nDid you mean to call e.g. \"serialize\" or \"unserialize\"? at /var/www/apibase.start/src/SB/UserBundle/Controller/UserController.php:63)"} []
[2016-03-27 23:04:19] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:04:19] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\AlreadySubmittedException: "A form can only be submitted once" at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 504 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\AlreadySubmittedException(code: 0): A form can only be submitted once at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:504)"} []
[2016-03-27 23:23:15] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:23:15] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "user"" at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php line 92 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"user\" at /var/www/apibase.start/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php:92)"} []
[2016-03-27 23:27:00] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:27:01] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "i8sdegz7uegoksk88owc84ok484ss8k", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"i8sdegz7uegoksk88owc84ok484ss8k\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:27:39] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:27:40] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "n2n0oepzjogkos8w4cw8wskkg4scck8", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"n2n0oepzjogkos8w4cw8wskkg4scck8\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:28:46] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:28:46] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "i0gw5qv33ncwk0wocw048s4ssogosw4", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"i0gw5qv33ncwk0wocw048s4ssogosw4\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:29:34] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:29:34] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "mezdlbe846s8ckoog8wggsk4okcoowc", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"mezdlbe846s8ckoog8wggsk4okcoowc\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:31:17] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:31:17] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "jwwwzkskxy8k0occskcc4sks8w0cgcw", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"jwwwzkskxy8k0occskcc4sks8w0cgcw\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:33:23] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:33:24] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "66dcfkzn1q80wk84s4ks88w0k4coc0k", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"66dcfkzn1q80wk84s4ks88w0k4coc0k\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:40:06] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:40:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "nsco29obwv4g08sok8804gkc8wgsggs", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"nsco29obwv4g08sok8804gkc8wgsggs\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:41:48] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:41:48] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "134ha7bfp51c4s80cooosskkgckwg0w", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"134ha7bfp51c4s80cooosskkgckwg0w\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:50:25] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:50:25] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "kisoek1mqn4k4s44kw4o48gg4koogkg", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"kisoek1mqn4k4s44kw4o48gg4koogkg\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:50:27] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:50:27] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "gzx765b2ogg8g88o0owk0oggs8cs4g0", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"gzx765b2ogg8g88o0owk0oggs8cs4g0\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:50:43] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:50:43] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "7dgqh0qp5vcwgssow0so0w4s4gwoccg", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"7dgqh0qp5vcwgssow0so0w4s4gwoccg\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:50:44] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:50:44] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "owggoilcedwogkco88k0wsggssg8wss", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"owggoilcedwogkco88k0wsggssg8wss\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:52:06] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:52:06] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["mario", "mario", "mario@mario.it", "mario@mario.it", 1, "rba69pd5u9cs8gkgck8osgoc888w4co", null, null, 0, 0, null, null, null, "a:0:{}", 0, null, "mario"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null" at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mario\", \"mario\", \"mario@mario.it\", \"mario@mario.it\", 1, \"rba69pd5u9cs8gkgck8osgoc888w4co\", null, null, 0, 0, null, null, null, \"a:0:{}\", 0, null, \"mario\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null at /var/www/apibase.start/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
[2016-03-27 23:52:18] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:52:18] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to SB\UserBundle\Form\Handler\RegistrationFormHandler::process() must be an instance of SB\UserBundle\Form\Handler\UserInterface, boolean given, called in /var/www/apibase.start/src/SB/UserBundle/Controller/RegistrationController.php on line 21 and defined" at /var/www/apibase.start/src/SB/UserBundle/Form/Handler/RegistrationFormHandler.php line 14 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to SB\\UserBundle\\Form\\Handler\\RegistrationFormHandler::process() must be an instance of SB\\UserBundle\\Form\\Handler\\UserInterface, boolean given, called in /var/www/apibase.start/src/SB/UserBundle/Controller/RegistrationController.php on line 21 and defined at /var/www/apibase.start/src/SB/UserBundle/Form/Handler/RegistrationFormHandler.php:14)"} []
[2016-03-27 23:52:33] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:52:33] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to SB\UserBundle\Form\Handler\RegistrationFormHandler::process() must be an instance of SB\UserBundle\Form\Handler\UserInterface, boolean given, called in /var/www/apibase.start/src/SB/UserBundle/Controller/RegistrationController.php on line 21 and defined" at /var/www/apibase.start/src/SB/UserBundle/Form/Handler/RegistrationFormHandler.php line 14 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to SB\\UserBundle\\Form\\Handler\\RegistrationFormHandler::process() must be an instance of SB\\UserBundle\\Form\\Handler\\UserInterface, boolean given, called in /var/www/apibase.start/src/SB/UserBundle/Controller/RegistrationController.php on line 21 and defined at /var/www/apibase.start/src/SB/UserBundle/Form/Handler/RegistrationFormHandler.php:14)"} []
[2016-03-27 23:53:18] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-27 23:53:18] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\Form\Handler\RegistrationFormHandler' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":807,"level":6143,"stack":[]} []
[2016-03-27 23:53:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "RegistrationFormHandler" from namespace "SB\UserBundle\Form\Handler". Did you forget a "use" statement for "FOS\UserBundle\Form\Handler\RegistrationFormHandler"?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 807 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"RegistrationFormHandler\" from namespace \"SB\\UserBundle\\Form\\Handler\".\nDid you forget a \"use\" statement for \"FOS\\UserBundle\\Form\\Handler\\RegistrationFormHandler\"? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:807)"} []
[2016-03-28 20:45:00] request.INFO: Matched route "fos_user_registration_register". {"route_parameters":{"_controller":"SB\\UserBundle\\Controller\\RegistrationController::registerAction","_route":"fos_user_registration_register"},"request_uri":"http://apibase.start/new"} []
[2016-03-28 20:45:01] php.CRITICAL: Fatal Error: Class 'SB\UserBundle\Form\Handler\RegistrationFormHandler' not found {"type":1,"file":"/var/www/apibase.start/app/cache/prod/appProdProjectContainer.php","line":807,"level":6143,"stack":[]} []
[2016-03-28 20:45:02] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "RegistrationFormHandler" from namespace "SB\UserBundle\Form\Handler". Did you forget a "use" statement for "FOS\UserBundle\Form\Handler\RegistrationFormHandler"?" at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php line 807 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"RegistrationFormHandler\" from namespace \"SB\\UserBundle\\Form\\Handler\".\nDid you forget a \"use\" statement for \"FOS\\UserBundle\\Form\\Handler\\RegistrationFormHandler\"? at /var/www/apibase.start/app/cache/prod/appProdProjectContainer.php:807)"} []
